// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIzzBJiP51hrIR1FleTmNkLCdCO3ytggg',
    appId: '1:712834459798:android:745f1e87daec3b3520fab7',
    messagingSenderId: '712834459798',
    projectId: 'la-recette-28025',
    storageBucket: 'la-recette-28025.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdtEeHpzL-sWI_y8BwC6KqLiEnrogUF0',
    appId: '1:712834459798:web:6053a78e4ce2917320fab7',
    messagingSenderId: '712834459798',
    projectId: 'la-recette-28025',
    authDomain: 'la-recette-28025.firebaseapp.com',
    storageBucket: 'la-recette-28025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD115MRdKSnmvNJoZlM1o3VrqgSANebD5I',
    appId: '1:712834459798:ios:d5aac6a3609caa5120fab7',
    messagingSenderId: '712834459798',
    projectId: 'la-recette-28025',
    storageBucket: 'la-recette-28025.appspot.com',
    iosClientId: '712834459798-38ge15f26ho4o6jdoo49bjknn4e0begi.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}